# Gunakan image resmi Node.js
FROM node:22

# Set direktori kerja di dalam container
WORKDIR /app

# Salin package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Salin semua file ke dalam container
COPY . .

WORKDIR /app/server

# Expose port (misal 3000)
EXPOSE 8080 

# Command untuk menjalankan app
CMD ["node", "server.js"]
